#!/bin/bash

rm h_b*.root 
rm l_b*.log

tseed=$(($(date +%s%N)/1000000-1393400000000))

echo $tseed

#./glxdirc -e 1000000 -s 1 -x "opticalphoton" -p "3.18 eV" -mr 800 -mt 16 -c 2 -g 0 -w 0 -b 1

for i in {0..4}; do ../build/glxdirc -o h_b$i.root -s 0 -e 2000  -x proton -p 4.5 -z -2 -gx -2180 -gy 200 -mr 800 -mt 16 -c 0 -w 10 -b 1 -r $tseed$i > l_b$i.log & done

sleep 1

while : 
do
    activth=$(ps aux | grep "[g]lx" | grep "h_b" | wc -l)
    diffth=$(($maxnthr-$activth))
    echo "We have $activth active glxdirc simulations" 
    if [ "$activth" -eq 0 ]; then 
      break  
    fi
    sleep 2
done

sleep 2
 
rm hits.root
hadd hits.root h_b*.root
