#!/bin/bash

rm h_b*.root 
rm l_b*.log

tseed=$(($(date +%s%N)/1000000-1393400000000))

echo $tseed

for i in {0..4}; do ../build/glxdirc -o h_b$i.root -s 0 -e 200 -s 0 -x "proton" -p 10 -z -2 -gx 2000 -gy 200 -mr 800 -mt 16 -b 1 -r $tseed$i > l_b$i.log & done

sleep 1

while : 
do
    activth=$(ps aux | grep "[g]lx" | grep "h_b" | wc -l)
    diffth=$(($maxnthr-$activth))
    echo "We have $activth active glxdirc simulations" 
    if [ "$activth" -eq 0 ]; then 
      break  
    fi
    sleep 2
done

sleep 2
 
rm hits.root
hadd hits.root h_b*.root
